---
- name: Import the public key for RVM
  become: yes
  become_user: "{{ username }}"
  shell: >
    gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  args:
    warn: no
    executable: /bin/bash
    chdir: "/home/{{ username }}"
  register: import_public_key_rvm

- debug:
    var: import_public_key_rvm
