galaxy_info:
  author: Nedim Hadzimahmutovic
  description: your description
  company: your company (optional)

  license: license (MIT)

  min_ansible_version: 2.4

  galaxy_tags: []

dependencies: []
